title: marcuwynu.com | Portfolio
email: wynumarcu23@example.com
description: >- # this means to ignore newlines until "baseurl:"
 sdasdsd
 
url: marcuwynu23.github.io
baseurl: /portfolio
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marcuwynu23
github_username:  marcuwynu23


include:
  - _includes


# Build settings
# theme: minima
# plugins:
#   - jekyll-feed
# Define custom layout
layouts_dir: "_layouts"
default_layout: "default"

# Custom layout values
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

port: 9000
